---
  - name: Create new local username and remove old username
    hosts: CSR1
    gather_facts: false
    tasks:
     - name: Remove explicity  username
        cisco.ios.ios_user:
          aggregate:
            - name: nw_automation
            - name: "{{new_username}}"
          purge: true

