---
  - name: Demo on simple test YAML script
    hosts: ciscoIOS
    gather_facts: no
    tasks:
      - name: capturing inetrface details
        cisco.ios.ios_command:
          commands:
            - show ip interace brief 
        register: output
      - name: Display output 
          msg: "{{output}}"

      
    
