ansible_host: 192.168.1.104
dns_server: 4.2.2.2
interface_details:
  - name: GigabitEthernet2
    desc: Connected to C8K1
    ip_address: 20.20.20.1
    mask: 255.255.255.0
  - name: GigabitEthernet3
    desc: Connected to CSR2
    ip_address: 50.50.50.1
    mask: 255.255.255.0
  - name: GigabitEthernet4
    desc: Connected to NXOS1 - faulty interface
    ip_address: 60.60.60.1
    mask: 255.255.255.0
device_role: router
