---
  - name: Demo on ios config and jinja2 template
    hosts: vIOS
    gather_facts: false
    tasks:
      - name: Demo on src
        cisco.ios.ios_config:
          src: Playbook/templates/full_config.j2
          save_when: changed
        register: out

      - name: Display output
        debug:
          msg: "{{out}}"
