---
  - name: Demo on Jinja2 template
    hosts: ciscoIOS
    gather_facts: no
    tasks:
      - name: Generate basic configuration
        template:
          src: device_basic_config.j2
          dest: "{{playbook_dir}}/config_files/{{inventory_hostname}}_basic_config.cfg"
