ansible_connection: network_cli
ansible_network_os: ios
ansible_user: nw_automation
ansible_password: devnet
ansible_become: true
ansible_become_method: enable
ansible_ssh_common_args: >
  -oHostkeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 -oMACs=+hmac-sha1,hmac-sha1-96
# dns_server: 8.8.8.8
ntp_server: 1.1.1.1
dhcp_server1: 1.1.1.1
dhcp_server2: 2.2.2.2
ntp_servers:
  - 1.1.1.1
  - 2.2.2.2
  - 3.3.3.3
